server:
  port: 5080
spring:
  application:
    name: consumer-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:5060/eureka/,http://eurekar2:5061/eureka/
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 1000




